apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: oauth2
  namespace: default
spec:
  httpPipeline:
    handlers:
    - name: okta
      type: middleware.http.oauth2clientcredentials
