service: <%= name %>

frameworkVersion: '2'

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    SERVICE_ENV: '${self:custom.stage}'
    SERVICE_NAME: '${self:service}'
  tags:
    env: '${self:custom.stage}'
    name: '${self:service}'

functions:
  run:
    handler: handler.run
